### PR TITLE
fix(storage): update storage to 2.0.0

### PR DESCRIPTION
**Pull request by pwespi**
Perform the steps from https://github.com/driftyco/ionic-storage/releases/tag/v2.0.0 to update storage to 2.0.0.

### CODE REVIEW

**Comment by azawawi** [comment]
Please merge this PR. I just tested it and it works perfectly 👍

**Comment by pwespi** [comment]
@mlynch sorry to nag, but as can be seen [here](https://github.com/driftyco/ionic-starter-super/issues/81), [here](https://forum.ionicframework.com/t/ionic-2-super-starter-shows-error-at-ionic-serve/82389/5) and [here](https://forum.ionicframework.com/t/ionic-2-super-starter-storage-error-straight-away/82403/2) a lot of users would benefit from this easy fix. The super-starter is not usable without it at the moment. Could you have a look?
Thanks for your great work!

**Comment by mlynch** [comment]
Will take a look once back from vacation

**Comment by pwespi** [comment]
Thanks! Hope your vacation isn't over yet... ;-)

**Comment by azawawi** [comment]
@mlynch Thanks a lot. Have a nice vacation 👍

**Pull request merged**
