### PR TITLE
Fixes issue #24

### LINKED ISSUE #24: Suggestion: Detect language to use in translation
I believe we should detect the device (browser) language, and use it with ng2-translate.

We should also provide the supported language list, and fallback to English if the detected language is not included in that list.

Should I submit a PR?

### PR DESCRIPTION
**Pull request by marcbruederlin**
Fixes #24.

### CODE REVIEW

**Comment by abennouna** [comment]
It doesn't work if the detected language is not supported: if browser language is 'xx', and there's no assets/i18n/xx.json file, it will raise a non-catchable 404 error and no translation will be used at all.

**Comment by abennouna** [comment]
A workaround would be to try to fetch (http.get) the json file from assets/i18n path:

- in case of success, use the detected language,
- in case of error, use 'en'

**Comment by marcbruederlin** [comment]
This bug should be fixed with ng2-translate 5.0.0.

**Comment by abennouna** [comment]
Should be, or is fixed? In my tests with 5.0.0 it is not.

**Comment by danielsogl** [comment]
I close this because we updated to ngx-translate. But thank you for your suggestions.

**Pull request closed without merging**
