### PR TITLE
fully translated starter

### PR DESCRIPTION
**Pull request by mikhail-irdeto**
except the mock data and pages you can not navigate to in this starter by default (which are currently "content" and "cards")

### CODE REVIEW

**Comment by mlynch** [comment]
Awesome, thanks! Will review soon

**Comment by mikhail-irdeto** [comment]
it affects the existing i18n assets though – the contributors who provided translations for the other languages will have to update their files accordingly...

**Comment by abennouna** [comment]
ng2-translate handles missing keys and falls back to the default language, so I see no harm (more in #47).

**Comment by mlynch** [comment]
Thanks!

**Pull request merged**
